### PR TITLE
Update cncf-projects.md - project list link(s)

### PR DESCRIPTION
**Pull request by whaber**
Should the project list contain links to each project?  (I updated the first one as an example).

If this is merged, I will make updates to the others.

### CODE REVIEW

**Comment by lumjjb** [comment]
This looks fine! Thanks @whaber , go ahead and do it for the entire list!

**Comment by whaber** [comment]
@lumjjb I added descriptions because each project's purpose is not well known.  It helps to gain interest in those projects.  That being said, the descriptions will change over time which will cause this content to lag.  I think the pros outweight the cons.  However, if you disagree, I can remove the descriptions.  Thanks.

**Comment by lumjjb** [comment]
What you've said is valid, and is actually part of what the security landscape hopes to do. (https://github.com/cncf/sig-security/blob/master/landscape/approach.md) - We are currently working on a revised Landscape v2, if you're interested to work on this (https://github.com/cncf/sig-security/issues/348)

I think the intent of this list is misunderstood. This list is not meant to be a resource for a link to a list of security projects. This is a list which the TOC specifically has made asks for us - which is used to determine assessment priority. This list is not meant to be a comprehensive list of security projects.

**Comment by whaber** [comment]
Thanks @lumjjb  I will close this and take a look at #348

**Pull request closed without merging**
