### PR TITLE
Modified Members section: Junyuan Zeng

### PR DESCRIPTION
**Pull request by jzeng4**
I added myself into the Members. Thanks!

### CODE REVIEW

**Comment by ultrasaurus** [comment]
Welcome! I didn't see your name in our meeting notes -- did I miss you? Would you like to join one of our online meetings or participate asynchronously in some way?

**Comment by jzeng4** [comment]
> Welcome! I didn't see your name in our meeting notes -- did I miss you? Would you like to join one of our online meetings or participate asynchronously in some way?

Hi Sarah

How to participate asynchronously? Thanks!

**Comment by lizrice** [comment]
Good question. We do have a channel in the CNCF Slack now; @dshaw do we record the meetings?

**Comment by ultrasaurus** [comment]
closing for now, if you have been active in the group please re-open with a note and link
if you want to get involved, join a meeting, comment on an issue and/or make a PR for content improvements -- we just migrated the repo from SAFE WG, so I'm sure there's lots of opportunity to fix things

**Pull request closed without merging**
