### PR TITLE
Updating to reflect the correct year when this assessment was conducted.

### PR DESCRIPTION
**Pull request by walmav**
Should the year be 2020 instead of 2019?

### CODE REVIEW

**Comment by walmav** [comment]
@anvega Please confirm

**Review by lumjjb — APPROVED** [review]
Looks right to me. Thanks!

**Comment by lumjjb** [comment]
Require code owners to approve. @JustinCappos @pragashj @ultrasaurus

**Comment by ultrasaurus** [comment]
yep! here's the history....
image

**Review by ultrasaurus — APPROVED** [review]
left comment with history snapshot -- approve!

**Pull request merged**
