### PR TITLE
Add Hamza2404 to the list

### PR DESCRIPTION
**Pull request by Hamza2404**

### CODE REVIEW

**Comment by pragashj** [comment]
Could you please identify with an org or some public profile please?

**Comment by Hamza2404** [comment]
@pragashj This is my professional email: hamza@nationalinjectionservices.co
Please add my company "National Injection Services" as marked in my Github account

**Comment by ultrasaurus** [comment]
Hello @Hamza2404 -- I didn't see you in the meeting notes.  Would you like to join a working group meeting or participate asynchronously in some way?

**Comment by ultrasaurus** [comment]
closing for now, if you have been active in the group please re-open with a note and link 
if you want to get involved, join a meeting, comment on an issue and/or make a PR for content improvements -- we just migrated the repo from SAFE WG, so I'm sure there's lots of opportunity to fix things

**Pull request closed without merging**
