### PR TITLE
Some additional categories to consider (#1)

### PR DESCRIPTION
**Pull request by gadinaor**
- cover cloud native security infrastructure security (kubernetes API server for example, Service Mesh control plane)
- detailed break down of workload protection
- add service discovery aspects

### CODE REVIEW

**Comment by JustinCappos** [comment]
FYI: There is an on-going discussion about taking a different approach with the landscape document.  We (@lumjjb ) will discuss and present in an upcoming meeting and try to take your edits into account.

**Comment by gadinaor** [comment]
@JustinCappos - thanks - is this taking on the weekly meeting ? I might be able to join if that’s possible

**Comment by lumjjb** [comment]
Tracking for this issue is now in https://github.com/cncf/sig-security/issues/348. Let's continue the conversation there!

**Comment by pragashj** [comment]
@gadinaor -- closing this out in favor of the whitepaper initiative -- do you might squashing this?

**Comment by magnologan** [comment]
Is this issue still relevant? it's been almost a year already.

**Comment by ultrasaurus** [comment]
closing this PR -- would need to be revisited in light of new whitepaper content, pls see issue #348.

**Pull request closed without merging**
