### PR TITLE
Fix mistakes in in-toto self-assessment

### PR DESCRIPTION
**Pull request by lukpueh**
Fixed a few mistakes, while reading the in-toto self-assessment, including
- typos/spelling
- full stops for consistency
- missing/wrong links
- excess whitespace

@SantiagoTorres, please note my change in [L382](https://github.com/cncf/sig-security/compare/master...lukpueh:fix_in-toto_assessment?expand=1#diff-39701274bea97973dc88cb502dfa9a77R382). You wrote "*artifact rules*", but I think you meant *"firewall rules"*, is this correct?

Thanks for the great write-up!

### CODE REVIEW

**Comment by SantiagoTorres** [comment]
> @SantiagoTorres, please note my change in L382. You wrote "artifact rules", but I think you meant "firewall rules", is this correct?

Nice catch! yes Indeed I meant "firewall rules"

**Comment by lukpueh** [comment]
> These changes are mostly cosmetic, although I don't know what the implications are for an already-reviewed assessment.

Yes, they are. Just thought, "if you see something, patch something". IMO the firewall thing and [L231](https://github.com/cncf/sig-security/pull/238/files#diff-39701274bea97973dc88cb502dfa9a77R231), which lacked a crucial *"not"*, are the only meaningful changes...

> I do think that at least fixing your last name (sorry about that! I was laser focused on putting the umlaut in the right place) is in order...

...and of course my name. But no worries about that. I myself sometimes mis-spell it. ;)

**Comment by ultrasaurus** [comment]
As a process point, I think it is fine to correct typos/spelling/consistency -- anything that doesn't affect the intent with review by author, though our official stance is:

"Security Reviewers should seek the approval of the other participating Security Reviewers and at least 1 co-chair before merging" -- https://github.com/cncf/sig-security/blob/master/assessments/guide/security-reviewer.md#expectations

So, since I think we've got everyone else on the team approved, I'll give it a review a little later today and we should be compliant with our policy.  cc @JustinCappos

**Comment by justincormack** [comment]
I think all are cosmetic or cover the intent. Sorry we didn't proof read very well!

**Comment by ultrasaurus** [comment]
Thanks @lumjjb for your attention to detail here.  The only change in meaning that was not mentioned in the PR review so far is python 2.7, 3.5, 3.6, 3.7 -- instead of Python 3.4.  Did a quick google search and appears correct based on https://pypi.org/project/in-toto/ --  might have been nice to link to canonical place for supported versions, but certainly not needed.

**Pull request merged**
