### PR TITLE
updated member list

### PR DESCRIPTION
**Pull request by unclepieman**
Added name to the members list

### CODE REVIEW

**Comment by lumjjb** [comment]
@unclepieman can you list some of your participation, i.e. in meetings, i can't find any records. tks.

**Comment by lumjjb** [comment]
Participation
- at least 3 meetings: 2020 Apr-May.

**Comment by lumjjb** [comment]
@unclepieman can you resolve conflicts and i can merge, tks!

**Comment by TheFoxAtWork** [comment]
@unclepieman please resolve the outstanding conflicts so we can get this merged in

**Comment by unclepieman** [comment]
> @unclepieman please resolve the outstanding conflicts so we can get this merged in

@TheFoxAtWork done, thanks.

**Pull request merged**
