### PR TITLE
Adding the SIG-Security color scheme

### PR DESCRIPTION
**Pull request by amye**
Adding SIG-security-color-scheme.pdf

### CODE REVIEW

**Comment by ultrasaurus** [comment]
Would it be possible to format this in HTML or something a bit easier to view than PDF?  (Hard to copy text / color values from PDF)

**Comment by lumjjb** [comment]
I was thinking of whether we should merge this first and make a new PR to convert this to HTML, but I think it would not be good to add tracking of a large blob like that. Should we create a suggestion to see if anyone wants to take up the task of converting this?

**Comment by alexcontini** [comment]
hi! I created the pdf and I thought something like this might work - https://github.com/alexcontini/sig-security/tree/master/logo ? Let me know if it looks okay or any feedback and we could either add that to the cncf repo in the sig security folder

**Comment by lumjjb** [comment]
@alexcontini That looks awesome!! Could you create a PR (referencing this one) and we can review and merge it! Thanks!

**Comment by lumjjb** [comment]
Addressed by https://github.com/cncf/sig-security/pull/339

**Pull request closed without merging**
